src/Presentation/SmartStore.Web/Models/ShoppingCart/ButtonPaymentMethodModel.cs
using System.Collections.Generic;
using System.Web.Routing;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.ShoppingCart
{
	public partial class ButtonPaymentMethodModel : ModelBase
	{
		public ButtonPaymentMethodModel()
		{
			Items = new List<ButtonPaymentMethodItem>();
		}

		public IList<ButtonPaymentMethodItem> Items { get; set; }

		public partial class ButtonPaymentMethodItem
		{
			public string ActionName { get; set; }
			public string ControllerName { get; set; }
			public RouteValueDictionary RouteValues { get; set; }
		}
	}
}

src/Presentation/SmartStore.Web/Models/ShoppingCart/EstimateShippingModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.ShoppingCart
{
    public partial class EstimateShippingModel : ModelBase
    {
        public EstimateShippingModel()
        {
            ShippingOptions = new List<ShippingOptionModel>();
            Warnings = new List<string>();
            
            AvailableCountries = new List<SelectListItem>();
            AvailableStates = new List<SelectListItem>();
        }

        public bool Enabled { get; set; }

		public string ShippingInfoUrl { get; set; }

        public IList<ShippingOptionModel> ShippingOptions { get; set; }

        public IList<string> Warnings { get; set; }
        
        [SmartResourceDisplayName("ShoppingCart.EstimateShipping.Country")]
        public int? CountryId { get; set; }
        [SmartResourceDisplayName("ShoppingCart.EstimateShipping.StateProvince")]
        public int? StateProvinceId { get; set; }
        [SmartResourceDisplayName("ShoppingCart.EstimateShipping.ZipPostalCode")]
        public string ZipPostalCode { get; set; }

        public IList<SelectListItem> AvailableCountries { get; set; }
        public IList<SelectListItem> AvailableStates { get; set; }

		#region Nested Classes

        public partial class ShippingOptionModel : ModelBase
        {
			public int ShippingMethodId { get; set; }

            public string Name { get; set; }

            public string Description { get; set; }

            public string Price { get; set; }
        }

		#endregion
    }
}

src/Presentation/SmartStore.Web/Models/ShoppingCart/MiniShoppingCartModel.cs
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Media;
using SmartStore.Web.Models.Catalog;
using System.Web.Mvc;
using SmartStore.Core.Domain.Catalog;
using System;
using SmartStore.Services.Localization;

namespace SmartStore.Web.Models.ShoppingCart
{
    public partial class MiniShoppingCartModel : ModelBase
    {
        public MiniShoppingCartModel()
        {
            Items = new List<ShoppingCartItemModel>();
        }

        public IList<ShoppingCartItemModel> Items { get; set; }
        public int TotalProducts { get; set; }
        public string SubTotal { get; set; }
        public bool DisplayCheckoutButton { get; set; }
        public bool CurrentCustomerIsGuest { get; set; }
        public bool AnonymousCheckoutAllowed { get; set; }
        public bool ShowProductImages { get; set; }
        public int ThumbSize { get; set; }
        public bool DisplayMoveToWishlistButton { get; set; }

        #region Nested Classes

        public partial class ShoppingCartItemModel : EntityModelBase, IQuantityInput
        {
            public ShoppingCartItemModel()
            {
                Picture = new PictureModel();
                BundleItems = new List<ShoppingCartItemBundleItem>();
                AllowedQuantities = new List<SelectListItem>();
            }

            public int ProductId { get; set; }

            public LocalizedValue<string> ProductName { get; set; }

            public LocalizedValue<string> ShortDesc { get; set; }

            public string ProductSeName { get; set; }

			public string ProductUrl { get; set; }
            
            public int EnteredQuantity { get; set; }

            public LocalizedValue<string> QuantityUnitName { get; set; }

            public List<SelectListItem> AllowedQuantities { get; set; }

            public int MinOrderAmount { get; set; }

            public int MaxOrderAmount { get; set; }

            public int QuantityStep { get; set; }

            public QuantityControlType QuantiyControlType { get; set; }

            public string UnitPrice { get; set; }

            public string AttributeInfo { get; set; }

            public PictureModel Picture { get; set; }

            public IList<ShoppingCartItemBundleItem> BundleItems { get; set; }

			public DateTime CreatedOnUtc { get; set; }

        }

        public partial class ShoppingCartItemBundleItem : ModelBase 
        {
            public string PictureUrl { get; set; }
            public LocalizedValue<string> ProductName { get; set; }
            public string ProductSeName { get; set; }
			public string ProductUrl { get; set; }
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Models/ShoppingCart/OffCanvasCartModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.ShoppingCart
{
    public partial class OffCanvasCartModel : ModelBase
    {
        // product counts
        public int CartItemsCount { get; set; }
        public int WishlistItemsCount { get; set; }
        public int CompareItemsCount { get; set; }

        // settings
        public bool ShoppingCartEnabled { get; set; }
        public bool WishlistEnabled { get; set; }
        public bool CompareProductsEnabled { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/ShoppingCart/OrderTotalsModel.cs
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.ShoppingCart
{
    public partial class OrderTotalsModel : ModelBase
    {
        public OrderTotalsModel()
        {
            TaxRates = new List<TaxRate>();
            GiftCards = new List<GiftCard>();
        }

        public bool IsEditable { get; set; }

        public string SubTotal { get; set; }

        public string SubTotalDiscount { get; set; }
        public bool AllowRemovingSubTotalDiscount { get; set; }

        public string Shipping { get; set; }
        public bool RequiresShipping { get; set; }
        public string SelectedShippingMethod { get; set; }

        public string PaymentMethodAdditionalFee { get; set; }

        public string Tax { get; set; }
        public IList<TaxRate> TaxRates { get; set; }
        public bool DisplayTax { get; set; }
        public bool DisplayTaxRates { get; set; }
        public bool DisplayWeight { get; set; }
        
        public IList<GiftCard> GiftCards { get; set; }

        public string OrderTotalDiscount { get; set; }
        public bool AllowRemovingOrderTotalDiscount { get; set; }
        public int RedeemedRewardPoints { get; set; }
        public string RedeemedRewardPointsAmount { get; set; }
		public string CreditBalance { get; set; }
		public string OrderTotalRounding { get; set; }
        public string OrderTotal { get; set; }
        public decimal Weight { get; set; }
        public string WeightMeasureUnitName { get; set; }

        public bool ShowConfirmOrderLegalHint { get; set; }
		public string MinOrderSubtotalWarning { get; set; }

		#region Nested classes

		public partial class TaxRate : ModelBase
        {
            public string Rate { get; set; }
            public string Value { get; set; }
			public string Label { get; set; }
        }

        public partial class GiftCard : EntityModelBase
        {
            public string CouponCode { get; set; }
            public string Amount { get; set; }
            public string Remaining { get; set; }
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Domain.Common;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Discounts;
using SmartStore.Core.Domain.Orders;
using SmartStore.Core.Domain.Payments;
using SmartStore.Core.Domain.Shipping;
using SmartStore.Core.Html;
using SmartStore.Core.Logging;
using SmartStore.Services.Catalog;
using SmartStore.Services.Common;
using SmartStore.Services.Customers;
using SmartStore.Services.Directory;
using SmartStore.Services.Localization;
using SmartStore.Services.Orders;
using SmartStore.Services.Payments;
using SmartStore.Services.Shipping;
using SmartStore.Services.Tax;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Filters;
using SmartStore.Web.Framework.Plugins;
using SmartStore.Web.Framework.Security;
using SmartStore.Web.Models.Checkout;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Controllers
{
    [RequireHttpsByConfigAttribute(SslRequirement.Yes)]
    public partial class CheckoutController : PublicControllerBase
    {
		#region Fields

        private readonly IWorkContext _workContext;
		private readonly IStoreContext _storeContext;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly ILocalizationService _localizationService;
        private readonly ITaxService _taxService;
        private readonly ICurrencyService _currencyService;
        private readonly IPriceFormatter _priceFormatter;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly ICustomerService _customerService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly ICountryService _countryService;
        private readonly IStateProvinceService _stateProvinceService;
        private readonly IShippingService _shippingService;
        private readonly IPaymentService _paymentService;
        private readonly IOrderTotalCalculationService _orderTotalCalculationService;
        private readonly IOrderService _orderService;
        private readonly HttpContextBase _httpContext;
        private readonly OrderSettings _orderSettings;
        private readonly PaymentSettings _paymentSettings;
        private readonly AddressSettings _addressSettings;
        private readonly ShippingSettings _shippingSettings;
        private readonly ShoppingCartSettings _shoppingCartSettings;
		private readonly PluginMediator _pluginMediator;

        #endregion

		#region Constructors

		public CheckoutController(
            IWorkContext workContext,
            IStoreContext storeContext,
            IShoppingCartService shoppingCartService, 
            ILocalizationService localizationService, 
            ITaxService taxService, 
            ICurrencyService currencyService, 
            IPriceFormatter priceFormatter, 
            IOrderProcessingService orderProcessingService,
            ICustomerService customerService,
            IGenericAttributeService genericAttributeService,
            ICountryService countryService,
            IStateProvinceService stateProvinceService, 
            IShippingService shippingService,
			IPaymentService paymentService, 
			IOrderTotalCalculationService orderTotalCalculationService,
            IOrderService orderService,
            HttpContextBase httpContext,
            OrderSettings orderSettings, 
            PaymentSettings paymentSettings,
            AddressSettings addressSettings,
            ShoppingCartSettings shoppingCartSettings,
            ShippingSettings shippingSettings,
			PluginMediator pluginMediator)
        {
            _workContext = workContext;
			_storeContext = storeContext;
            _shoppingCartService = shoppingCartService;
            _localizationService = localizationService;
            _taxService = taxService;
            _currencyService = currencyService;
            _priceFormatter = priceFormatter;
            _orderProcessingService = orderProcessingService;
            _customerService = customerService;
            _genericAttributeService = genericAttributeService;
            _countryService = countryService;
            _stateProvinceService = stateProvinceService;
            _shippingService = shippingService;
            _paymentService = paymentService;
            _orderTotalCalculationService = orderTotalCalculationService;
            _orderService = orderService;
            _httpContext = httpContext;
            _orderSettings = orderSettings;
            _paymentSettings = paymentSettings;
            _addressSettings = addressSettings;
            _shippingSettings = shippingSettings;
            _shoppingCartSettings = shoppingCartSettings;
			_pluginMediator = pluginMediator;
        }

        #endregion

        #region Utilities

        [NonAction]
		protected bool IsPaymentWorkflowRequired(IList<OrganizedShoppingCartItem> cart, bool ignoreRewardPoints = false)
        {
            // Check whether order total equals zero
            decimal? shoppingCartTotalBase = _orderTotalCalculationService.GetShoppingCartTotal(cart, ignoreRewardPoints);

            if (shoppingCartTotalBase.HasValue && shoppingCartTotalBase.Value == decimal.Zero)
                return false;

			if (_httpContext.GetCheckoutState().IsPaymentSelectionSkipped)
				return false;

            return true;
        }

        [NonAction]
        protected CheckoutBillingAddressModel PrepareBillingAddressModel(int? selectedCountryId = null)
        {
            var customer = _workContext.CurrentCustomer;
            var model = new CheckoutBillingAddressModel();
            
            // Existing addresses.
            var addresses = customer.Addresses.Where(a => a.Country == null || a.Country.AllowsBilling).ToList();
            foreach (var address in addresses)
            {
                var addressModel = new AddressModel();
                addressModel.PrepareModel(address, false, _addressSettings);
                model.ExistingAddresses.Add(addressModel);
            }

            // New address.
            model.NewAddress.CountryId = selectedCountryId;
            model.NewAddress.PrepareModel(null,
                false,
                _addressSettings,
                _localizationService,
                _stateProvinceService,
                () => _countryService.GetAllCountriesForBilling());
            model.NewAddress.Email = customer?.Email;

            return model;
        }

        [NonAction]
        protected CheckoutShippingAddressModel PrepareShippingAddressModel(int? selectedCountryId = null)
        {
            var customer = _workContext.CurrentCustomer;
            var model = new CheckoutShippingAddressModel();
            
            // Existing addresses.
            var addresses = customer.Addresses.Where(a => a.Country == null || a.Country.AllowsShipping).ToList();
            foreach (var address in addresses)
            {
                var addressModel = new AddressModel();
                addressModel.PrepareModel(address, false, _addressSettings);
                model.ExistingAddresses.Add(addressModel);
            }

            // New address.
            model.NewAddress.CountryId = selectedCountryId;
            model.NewAddress.PrepareModel(null,
                false,
                _addressSettings,
                _localizationService,
                _stateProvinceService,
                () => _countryService.GetAllCountriesForShipping());
            model.NewAddress.Email = customer?.Email;

            return model;
        }

		[NonAction]
		protected CheckoutShippingMethodModel PrepareShippingMethodModel(IList<OrganizedShoppingCartItem> cart)
		{
			var model = new CheckoutShippingMethodModel();

			var store = _storeContext.CurrentStore;
			var customer = _workContext.CurrentCustomer;
			var getShippingOptionResponse = _shippingService.GetShippingOptions(cart, customer.ShippingAddress, "", store.Id);

			if (getShippingOptionResponse.Success)
			{
				// Performance optimization. cache returned shipping options.
				// We'll use them later (after a customer has selected an option).
				_genericAttributeService.SaveAttribute(customer, SystemCustomerAttributeNames.OfferedShippingOptions, getShippingOptionResponse.ShippingOptions, store.Id);

				var shippingMethods = _shippingService.GetAllShippingMethods(null, store.Id);

				foreach (var shippingOption in getShippingOptionResponse.ShippingOptions)
				{
					var soModel = new CheckoutShippingMethodModel.ShippingMethodModel
					{
						ShippingMethodId = shippingOption.ShippingMethodId,
						Name = shippingOption.Name,
						Description = shippingOption.Description,
						ShippingRateComputationMethodSystemName = shippingOption.ShippingRateComputationMethodSystemName,
					};

					var srcmProvider = _shippingService.LoadShippingRateComputationMethodBySystemName(shippingOption.ShippingRateComputationMethodSystemName);
					if (srcmProvider != null)
					{
						soModel.BrandUrl = _pluginMediator.GetBrandImageUrl(srcmProvider.Metadata);
					}

					// Adjust rate.
					Discount appliedDiscount = null;
					var shippingTotal = _orderTotalCalculationService.AdjustShippingRate(shippingOption.Rate, cart, shippingOption, shippingMethods, out appliedDiscount);
					decimal rateBase = _taxService.GetShippingPrice(shippingTotal, customer);
					decimal rate = _currencyService.ConvertFromPrimaryStoreCurrency(rateBase, _workContext.WorkingCurrency);
					soModel.FeeRaw = rate;
					soModel.Fee = _priceFormatter.FormatShippingPrice(rate, true);

					model.ShippingMethods.Add(soModel);
				}

				// Find a selected (previously) shipping method.
				var selectedShippingOption = customer.GetAttribute<ShippingOption>(SystemCustomerAttributeNames.SelectedShippingOption, store.Id);
				if (selectedShippingOption != null)

src/Presentation/SmartStore.Web/Views/ShoppingCart/Cart.cshtml
@model ShoppingCartModel
@using SmartStore.Web.Models.Checkout
@using SmartStore.Web.Models.ShoppingCart;
@{
    Layout = "_Checkout";
    Html.AddBodyCssClass("order-summary-page no-offcanvas-cart");
    Html.AddTitleParts(T("PageTitle.ShoppingCart").Text);
}

@section orderProgress{
	@{ Html.RenderAction("CheckoutProgress", "Checkout", new { step = CheckoutProgressStep.Cart }); }
}

<div class="page shopping-cart-page">
    <div class="page-title">
        <h1 class="h3">@T("ShoppingCart")</h1>
    </div>
    <div class="page-body">
        @{ Html.RenderPartial("OrderSummary", Model); }
    </div>
</div>

src/Presentation/SmartStore.Web/Views/ShoppingCart/EmailWishlist.cshtml
@model WishlistEmailAFriendModel

@using SmartStore.Web.Models.ShoppingCart;

@{
    Layout = "_Layout";

    Html.AddTitleParts(T("PageTitle.WishlistEmailAFriend").Text);
}

<div class="page email-a-friend-page">
    <div class="page-title">
        <h1>@T("Wishlist.EmailAFriend.Title")</h1>
    </div>
    <div class="page-body">
        @if (Model.SuccessfullySent)
        {
            <div class="result">
                @Model.Result
            </div>
        }
        else
        {
            using (Html.BeginForm("EmailWishlist", null, FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <fieldset>
                    <p class="message-error">
						@if (!ViewData.ModelState.IsValid)
						{
							@Html.ValidationSummary(true)
						}
                    </p>
                
                    <div class="form-group">
                        @Html.LabelFor(model => model.FriendEmail, new { @for = "FriendEmail", @class = "col-form-label required" })
                        @Html.TextBoxFor(model => model.FriendEmail, new { @class = "friend-email form-control", placeholder = T("Wishlist.EmailAFriend.FriendEmail.Hint") })
                        @Html.ValidationMessageFor(model => model.FriendEmail)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.YourEmailAddress, new { @for = "YourEmailAddress", @class = "col-form-label required" })
                        @Html.TextBoxFor(model => model.YourEmailAddress, new { @class = "your-email form-control", placeholder = T("Wishlist.EmailAFriend.YourEmailAddress.Hint") })
                        @Html.ValidationMessageFor(model => model.YourEmailAddress)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PersonalMessage, new { @for = "PersonalMessage", @class = "col-form-label" })
                        @Html.TextAreaFor(model => model.PersonalMessage, new { @class = "personal-message form-control", placeholder = T("Wishlist.EmailAFriend.PersonalMessage.Hint") })
                        @Html.ValidationMessageFor(model => model.PersonalMessage)
                    </div>

                    <div class="form-group row">
                        <div class="col-12 text-muted">
                            @T("Common.FormFields.Required.Hint")
                        </div>
                    </div>

					@{ Html.RenderWidget("gdpr_consent"); }

                    @if (Model.DisplayCaptcha)
                    {
						<div class="form-group">
							<div class="captcha-box">
								@Html.Raw(Html.GenerateCaptcha())
							</div>
						</div>
                    }
                
                    <input type="hidden" name="send-email" value="send-email">

                    <div class="form-group">
                        <button type="submit" name="send-email" class="btn btn-primary send-email-a-friend-button">@T("Wishlist.EmailAFriend.Button")</button>
                    </div>

                </fieldset>
            }
        }
    </div>
</div>

src/Presentation/SmartStore.Web/Views/ShoppingCart/Wishlist.cshtml
@model WishlistModel
@using SmartStore.Web.Models.ShoppingCart;
@{
    Layout = "_Layout";
    Html.AddTitleParts(T("PageTitle.Wishlist").Text);
    Html.AddBodyCssClass("no-offcanvas-cart");
}

<div class="page wishlist-page">
    <div class="page-title">
        <h1>@(Model.IsEditable ? T("Wishlist") : T("Wishlist.WishlistOf", Model.CustomerFullname))</h1>
    </div>
    <div class="page-body">
        <div class="wishlist-content cart-content" data-empty-text=@T("Wishlist.CartIsEmpty").JsText>
            
            @{ Html.RenderWidget("wishlist_items_top"); }

            @if (Model.Items.Count > 0)
            {
                if (Model.Warnings.Count > 0)
                {
                    <div class="alert alert-danger">
                        @for (int i = 0; i < Model.Warnings.Count; i++)
                        {
                            <p>@Model.Warnings[i]</p>
                        }
                    </div>
                }

                using (Html.BeginRouteForm("Wishlist", FormMethod.Post))
                {
                    <div class="card mb-4">
                        <div id="cart-items" class="cart cart-editable mb-0">
                            <div class="cart-head">
                                <div class="cart-row">
                                    <div class="cart-col cart-col-main">
                                        @T("ShoppingCart.Product(s)")
                                    </div>
                                    <div class="cart-col cart-col-price">
                                        @T("ShoppingCart.UnitPrice")
                                    </div>
                                    <div class="cart-col cart-col-qty">
                                        @T("ShoppingCart.Quantity")
                                    </div>
                                    <div class="cart-col cart-col-price cart-col-subtotal">
                                        @T("ShoppingCart.ItemTotal")
                                    </div>
                                </div>
                            </div>
                            <div class="cart-body">
                                @{ Html.RenderPartial("WishlistItems", Model); }
                            </div>
                        </div>
                    </div>

                    <div class="common-buttons clearfix">
                        @if (Model.IsEditable && Model.EmailWishlistEnabled)
                        {
                            <a class="btn btn-secondary email-a-friend-wishlist-button" href="@Url.Action("EmailWishlist")" rel="nofollow">
                                <i class="fa fa-envelope"></i>
                                <span>@T("Wishlist.EmailAFriend")</span>
                            </a>
                        }
                        @if (Model.DisplayAddToCart && !Model.IsEditable)
                        {
                            <button type="submit" name="addtocartbutton" value="addtocartbutton" class="btn btn-primary wishlist-add-to-cart-button">
                                <i class="fa fa-cart-arrow-down"></i>
                                <span>@T("ShoppingCart.AddToCart")</span>
                            </button>
                        }						
                    </div>
                }
            }
            else
            {
				<div class="alert alert-warning fade show">
					@T("Wishlist.CartIsEmpty")
				</div>
            }
        </div>

        @if (Model.IsEditable && Model.Items.Count > 0)
        {
            <div class="share-info my-5">
                <h4 class="share-label">
					<i class="far fa-share-square"></i>
                    @T("Wishlist.YourWishlistURL")
                </h4>
                <a href="@Url.RouteUrl("Wishlist", new { customerGuid = Model.CustomerGuid })" class="share-link">
                    @Url.RouteUrl("Wishlist", new { customerGuid = Model.CustomerGuid }, "http")
                </a>
            </div>
        }
    </div>
</div>

@if (Model.IsEditable)
{
	Html.RenderPartial("_RefreshCartScript");
}