src/Presentation/SmartStore.Web/Models/Customer/AccountActivationModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class AccountActivationModel : ModelBase
    {
        public string Result { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/BackInStockSubscriptionModel.cs
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class BackInStockSubscriptionModel : EntityModelBase
    {
        public int ProductId { get; set; }
        public LocalizedValue<string> ProductName { get; set; }
        public string SeName { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/ChangePasswordModel.cs
using System.ComponentModel.DataAnnotations;
using FluentValidation;
using FluentValidation.Attributes;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Localization;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
	[Validator(typeof(ChangePasswordValidator))]
    public partial class ChangePasswordModel : ModelBase
    {
        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.OldPassword")]
        public string OldPassword { get; set; }

        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.NewPassword")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.ConfirmNewPassword")]
        public string ConfirmNewPassword { get; set; }

        public string Result { get; set; }
    }

    public class ChangePasswordValidator : AbstractValidator<ChangePasswordModel>
    {
        public ChangePasswordValidator(Localizer T, CustomerSettings customerSettings)
        {
            RuleFor(x => x.OldPassword).NotEmpty();
            RuleFor(x => x.NewPassword).NotEmpty();
            RuleFor(x => x.ConfirmNewPassword).NotEmpty();
            RuleFor(x => x.NewPassword).Length(customerSettings.PasswordMinLength, 999);

            RuleFor(x => x.ConfirmNewPassword).Equal(x => x.NewPassword).WithMessage(T("Account.ChangePassword.Fields.NewPassword.EnteredPasswordsDoNotMatch"));
        }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAddressEditModel.cs
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAddressEditModel : ModelBase
    {
        public CustomerAddressEditModel()
        {
            this.Address = new AddressModel();
        }
        public AddressModel Address { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAddressListModel.cs
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAddressListModel : ModelBase
    {
        public CustomerAddressListModel()
        {
            Addresses = new List<AddressModel>();
        }

        public IList<AddressModel> Addresses { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAvatarModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAvatarModel : ModelBase
    {
        public bool Large { get; set; }
        public string PictureUrl { get; set; }
        public string LinkUrl { get; set; }
        public string AvatarColor { get; set; }
        public char AvatarLetter { get; set; }
        public string UserName { get; set; }
    }

    public partial class CustomerAvatarEditModel : ModelBase
    {
		public string MaxFileSize { get; set; }
        public CustomerAvatarModel Avatar { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerBackInStockSubscriptionsModel.cs
using System.Collections.Generic;
using SmartStore.Core;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerBackInStockSubscriptionsModel : PagedListBase
    {
        public CustomerBackInStockSubscriptionsModel(IPageable pageable) : base(pageable)
        {
            this.Subscriptions = new List<BackInStockSubscriptionModel>();
        }

        public IList<BackInStockSubscriptionModel> Subscriptions { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerDownloadableProductsModel.cs
using System;
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Services.Localization;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerDownloadableProductsModel : ModelBase
    {
        public CustomerDownloadableProductsModel()
        {
            Items = new List<DownloadableProductsModel>();
        }

        public IList<DownloadableProductsModel> Items { get; set; }

        #region Nested classes

        public partial class DownloadableProductsModel : ModelBase
        {
            public DownloadableProductsModel()
            {
                DownloadVersions = new List<DownloadVersion>();
            }

            public Guid OrderItemGuid { get; set; }

            public int OrderId { get; set; }

            public int ProductId { get; set; }
            public LocalizedValue<string> ProductName { get; set; }
            public string ProductSeName { get; set; }
			public string ProductUrl { get; set; }
            public string ProductAttributes { get; set; }

            public int LicenseId { get; set; }
            public bool IsDownloadAllowed { get; set; }

            public DateTime CreatedOn { get; set; }

            public List<DownloadVersion> DownloadVersions { get; set; }
        }

        #endregion
    }

    public partial class UserAgreementModel : ModelBase
    {
        public Guid OrderItemGuid { get; set; }
        public string UserAgreementText { get; set; }
        public string FileVersion { get; set; }
    }

    public class DownloadVersion
    {
        public int DownloadId { get; set; }
        public string FileName { get; set; }
        public Guid DownloadGuid { get; set; }
        public string FileVersion { get; set; }
        public string Changelog { get; set; }
    }

}

src/Presentation/SmartStore.Web/Models/Customer/CustomerForumSubscriptionsModel.cs
using System.Collections.Generic;
using SmartStore.Core;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerForumSubscriptionsModel : PagedListBase
    {
        public CustomerForumSubscriptionsModel(IPageable pageable) : base(pageable)
        {
            this.ForumSubscriptions = new List<ForumSubscriptionModel>();
        }

        public IList<ForumSubscriptionModel> ForumSubscriptions { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerOrderListModel.cs
using System;
using System.Collections.Generic;
using SmartStore.Core;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
	public partial class CustomerOrderListModel : ModelBase
    {
        public CustomerOrderListModel()
        {
			RecurringOrders = new List<RecurringOrderModel>();
			CancelRecurringPaymentErrors = new List<string>();
        }

        public PagedList<OrderDetailsModel> Orders { get; set; }
        public IList<RecurringOrderModel> RecurringOrders { get; set; }
        public IList<string> CancelRecurringPaymentErrors { get; set; }

        #region Nested classes

        public partial class OrderDetailsModel : EntityModelBase
        {
            public string OrderNumber { get; set; }
            public string OrderTotal { get; set; }
            public bool IsReturnRequestAllowed { get; set; }
            public string OrderStatus { get; set; }
            public DateTime CreatedOn { get; set; }
        }

        public partial class RecurringOrderModel : EntityModelBase
        {
            public string StartDate { get; set; }
            public string CycleInfo { get; set; }
            public string NextPayment { get; set; }
            public int TotalCycles { get; set; }
            public int CyclesRemaining { get; set; }
            public int InitialOrderId { get; set; }
            public bool CanCancel { get; set; }
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerReturnRequestsModel.cs
using System;
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Services.Localization;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerReturnRequestsModel : ModelBase
    {
        public CustomerReturnRequestsModel()
        {
            Items = new List<ReturnRequestModel>();
        }

        public IList<ReturnRequestModel> Items { get; set; }

        #region Nested classes

        public partial class ReturnRequestModel : EntityModelBase
        {
            public string ReturnRequestStatus { get; set; }
            public int ProductId { get; set; }
            public LocalizedValue<string> ProductName { get; set; }
            public string ProductSeName { get; set; }
			public string ProductUrl { get; set; }
            public int Quantity { get; set; }

            public string ReturnReason { get; set; }
            public string ReturnAction { get; set; }
            public string Comments { get; set; }

            public DateTime CreatedOn { get; set; }
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerRewardPointsModel.cs
using System;
using System.Collections.Generic;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerRewardPointsModel : ModelBase
    {
        public CustomerRewardPointsModel()
        {
            RewardPoints = new List<RewardPointsHistoryModel>();
        }

        public IList<RewardPointsHistoryModel> RewardPoints { get; set; }
        public string RewardPointsBalance { get; set; }

        #region Nested classes
        public partial class RewardPointsHistoryModel : EntityModelBase
        {
            [SmartResourceDisplayName("RewardPoints.Fields.Points")]
            public int Points { get; set; }

            [SmartResourceDisplayName("RewardPoints.Fields.PointsBalance")]
            public int PointsBalance { get; set; }

            [SmartResourceDisplayName("RewardPoints.Fields.Message")]
            public string Message { get; set; }

			[SmartResourceDisplayName("Common.CreatedOn")]
            public DateTime CreatedOn { get; set; }
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Models/Customer/ExternalAuthenticationMethodModel.cs
using System.Web.Routing;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class ExternalAuthenticationMethodModel : ModelBase
    {
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public RouteValueDictionary RouteValues { get; set; }
    }
}

src/Presentation/SmartStore.Web/Controllers/PollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Caching;
using SmartStore.Core.Domain.Polls;
using SmartStore.Services.Customers;
using SmartStore.Services.Polls;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Models.Polls;

namespace SmartStore.Web.Controllers
{
	public partial class PollController : PublicControllerBase
    {
        #region Fields

        private readonly IWorkContext _workContext;
        private readonly IPollService _pollService;
        private readonly IWebHelper _webHelper;
        private readonly ICacheManager _cacheManager;
		private readonly IStoreContext _storeContext;

        #endregion

        #region Constructors

        public PollController(
            IWorkContext workContext,
			IPollService pollService,
            IWebHelper webHelper,
			ICacheManager cacheManager,
			IStoreContext storeContext)
        {
            this._workContext = workContext;
            this._pollService = pollService;
            this._webHelper = webHelper;
            this._cacheManager = cacheManager;
			this._storeContext = storeContext;
        }

        #endregion

        #region Utilities

        [NonAction]
        protected PollModel PreparePollModel(Poll poll, bool setAlreadyVotedProperty)
        {
            var model = new PollModel
            {
                Id = poll.Id,
                AlreadyVoted = setAlreadyVotedProperty && _pollService.AlreadyVoted(poll.Id, _workContext.CurrentCustomer.Id),
                Name = poll.Name
            };

            var answers = poll.PollAnswers.OrderBy(x => x.DisplayOrder);

			foreach (var answer in answers)
			{
				model.TotalVotes += answer.NumberOfVotes;
			}

            foreach (var pa in answers)
            {
                model.Answers.Add(new PollAnswerModel
                {
                    Id = pa.Id,
                    Name = pa.Name,
                    NumberOfVotes = pa.NumberOfVotes,
                    PercentOfTotalVotes = model.TotalVotes > 0 ? ((Convert.ToDouble(pa.NumberOfVotes) / Convert.ToDouble(model.TotalVotes)) * Convert.ToDouble(100)) : 0,
                });
            }

            return model;
        }

        #endregion

        #region Methods

        [ChildActionOnly]
        public ActionResult PollBlock(string systemKeyword)
        {
            if (String.IsNullOrWhiteSpace(systemKeyword))
                return Content("");

            var cacheKey = string.Format(ModelCacheEventConsumer.POLL_BY_SYSTEMNAME_MODEL_KEY, systemKeyword, _workContext.WorkingLanguage.Id, _storeContext.CurrentStore.Id);
            var cachedModel = _cacheManager.Get(cacheKey, () =>
            {
                var poll = _pollService.GetPollBySystemKeyword(systemKeyword, _workContext.WorkingLanguage.Id);

                if (poll == null)
					return new PollModel { Id = 0 };	//we do not cache nulls. that's why let's return an empty record (ID = 0)

                return PreparePollModel(poll, false);
            });

            if (cachedModel == null || cachedModel.Id == 0)
                return Content("");

            //"AlreadyVoted" property of "PollModel" object depends on the current customer. Let's update it.
            //But first we need to clone the cached model (the updated one should not be cached)
            var model = (PollModel)cachedModel.Clone();
            model.AlreadyVoted = _pollService.AlreadyVoted(model.Id, _workContext.CurrentCustomer.Id);
            model.SystemKeyword = systemKeyword;

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Vote(int pollAnswerId)
        {
            var pollAnswer = _pollService.GetPollAnswerById(pollAnswerId);

			if (pollAnswer == null)
			{
				return Json(new	{ error = T("Polls.AnswerNotFound", pollAnswerId).Text });
			}

            var poll = pollAnswer.Poll;

			if (!poll.Published)
			{
				return Json(new	{ error = T("Polls.NotAvailable").Text });
			}

			if (_workContext.CurrentCustomer.IsGuest() && !poll.AllowGuestsToVote)
			{
				return Json(new	{ error = T("Polls.OnlyRegisteredUsersVote").Text });
			}

            bool alreadyVoted = _pollService.AlreadyVoted(poll.Id, _workContext.CurrentCustomer.Id);
            if (!alreadyVoted)
            {
                //vote
                pollAnswer.PollVotingRecords.Add(new PollVotingRecord
                {
                    PollAnswerId = pollAnswer.Id,
                    CustomerId = _workContext.CurrentCustomer.Id,
                    IpAddress = _webHelper.GetCurrentIpAddress(),
                    IsApproved = true
                });

                //update totals
                pollAnswer.NumberOfVotes = pollAnswer.PollVotingRecords.Count;

                _pollService.UpdatePoll(poll);
            }

            return Json(new
            {
                html = this.RenderPartialViewToString("_Poll", PreparePollModel(poll, true)),
            });
        }
        
        [ChildActionOnly]
        public ActionResult HomePagePolls()
        {
            var cacheKey = string.Format(ModelCacheEventConsumer.HOMEPAGE_POLLS_MODEL_KEY, _workContext.WorkingLanguage.Id, _storeContext.CurrentStore.Id);
            var cachedModel = _cacheManager.Get(cacheKey, () =>
            {
                return _pollService.GetPolls(_workContext.WorkingLanguage.Id, true, 0, int.MaxValue)
                    .Select(x => PreparePollModel(x, false))
                    .ToList();
            });

            //"AlreadyVoted" property of "PollModel" object depends on the current customer. Let's update it.
            //But first we need to clone the cached model (the updated one should not be cached)
            var model = new List<PollModel>();

            foreach (var p in cachedModel)
            {
                var pollModel = (PollModel)p.Clone();
                pollModel.AlreadyVoted = _pollService.AlreadyVoted(pollModel.Id, _workContext.CurrentCustomer.Id);
                pollModel.SystemKeyword = "Homepage";
                model.Add(pollModel);
            }

			if (model.Count == 0)
				return Content("");

            return PartialView(model);
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Views/Customer/Partials/MyAccountMenu.cshtml
@model MyAccountMenuModel     
	      
@using SmartStore.Web.Models.Customer;

@{ 
	var selItem = Model.SelectedItemToken != null ? Model.SelectedItemToken.ToLowerInvariant() : "";
}

@{ Html.RenderWidget("myaccount_menu_before"); }

<div class="card myaccount-menu">
    <h5 class="card-header" style="border-bottom: none">
        @T("Account.Navigation")
    </h5>
	<div class="list-group list-group-flush has-icons">
		@{ Html.RenderWidget("myaccount_menu_firstitem_before"); }

		@foreach (var item in Model.Root.Children.Where(x => x.Value.Visible).Select(x => x.Value))
		{
			<a href="@item.Url" rel="nofollow" class="list-group-item list-group-item-action@(selItem.IsCaseInsensitiveEqual(item.Id) ? " active" : "")">
                <i class="fal fa-fw fa-@item.Icon list-group-item-icon"></i>
                <span>@item.Text</span>
                @if (item.BadgeText.HasValue())
                {
                    <span class="badge badge-pill badge-@item.BadgeStyle.ToString().ToLower() ml-auto">@Html.Raw(item.BadgeText)</span>
                }
            </a>
		}

		@{ Html.RenderWidget("myaccount_menu_lastitem_after"); }
	</div>
</div>

@{ Html.RenderWidget("myaccount_menu_after"); }

@{ Html.RenderAction("PollBlock", "Poll", new { systemKeyword = "MyAccountMenu" }); }

src/Presentation/SmartStore.Web/Views/Customer/Partials/_CheckUsernameAvailability.cshtml
<script type="text/javascript">
    $(function () {
    	$('#Username').closest(".input-group-append").after(createCircularSpinner(24).attr('id', 'cua-loader').css('margin-left', '10px'));
    	$('#Username').on('input propertychange paste', function (e) {
    		$('#username-availabilty').text('');
    		$('#check-availability-button')
				.removeClass("btn-success btn-warning")
				.addClass("btn-secondary")
				.find(">i")
				.removeClass("fa-check fa-exclamation-circle")
				.addClass("fa-question-circle");
    	});
        $('#check-availability-button').on('click', function (e) {
            var btn = $('#check-availability-button');
            $('#username-availabilty').text('');
            if ($("#Username").val().length > 0) {
                $('#cua-loader').addClass("active");
                btn.attr('disabled', 'disabled');
                $.ajax({
                    cache: false,
                    type: 'POST',
                    url: '@Url.Action("CheckUsernameAvailability")',
                    data: $('#Username').serialize(),
                    dataType: 'json',
                    success: function (data) {
                        btn.removeAttr('disabled');
                        btn
                            .removeClass("btn-success btn-warning btn-secondary")
                            .addClass(data.Available ? "btn-success" : "btn-warning")
                            .find(">i")
                            .removeClass("fa-check fa-question-circle fa-exclamation-circle")
                            .addClass(data.Available ? "fa-check" : "fa-exclamation-circle");

                        displayNotification(data.Text, data.Available ? "success" : "error");
                    },
                    complete: function () {
                        btn.removeAttr('disabled');
                        $('#cua-loader').removeClass("active");
                    }
                });
            } else {
                $('#username-availabilty').attr('class', 'not-available-status');
                $('#username-availabilty').text('*');
            }
            return false;
        });
    });
</script>

<span class="input-group-append">
	<button type="button" id="check-availability-button" class="btn btn-secondary check-username-availability-button tooltip-toggle" title="@T("Account.CheckUsernameAvailability.Button")">
		<i class="fa fa-question-circle"></i>
	</button>
</span>

src/Presentation/SmartStore.Web/Views/Customer/Partials/_ExternalAuthentication.AssociateMessage.cshtml
@using SmartStore.Services.Authentication.External;

@{
    var openAuthParameters = ExternalAuthorizerHelper.RetrieveParametersFromRoundTrip(false);
}

@if (openAuthParameters != null)
{
    <div class="alert alert-warning external-auth-association">
        @T("Account.AssociatedExternalAuth.YourAccountWillBeLinkedTo") <strong class="identifier">@openAuthParameters.ExternalIdentifier</strong>
		<a href="@Url.Action("RemoveParameterAssociation", "ExternalAuthentication", new { ReturnUrl = Request.Url.ToString() })" class="remove" rel="nofollow">
			@T("Common.Remove")
		</a>            
    </div>
}