src/Presentation/SmartStore.Web/Administration/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Xml;
using System.Data.Entity;
using Autofac;
using Newtonsoft.Json;
using SmartStore.Admin.Models.Localization;
using SmartStore.Core;
using SmartStore.Core.Async;
using SmartStore.Core.Domain.Common;
using SmartStore.Core.Domain.DataExchange;
using SmartStore.Core.Domain.Localization;
using SmartStore.Core.Logging;
using SmartStore.Core.Plugins;
using SmartStore.Services;
using SmartStore.Services.Common;
using SmartStore.Services.Directory;
using SmartStore.Services.Helpers;
using SmartStore.Services.Localization;
using SmartStore.Services.Security;
using SmartStore.Services.Stores;
using SmartStore.Utilities;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Filters;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Framework.Security;
using Telerik.Web.Mvc;

namespace SmartStore.Admin.Controllers
{
	[AdminAuthorize]
    public partial class LanguageController : AdminControllerBase
    {
        #region Fields

        private readonly ILanguageService _languageService;
		private readonly IStoreMappingService _storeMappingService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly AdminAreaSettings _adminAreaSettings;
		private readonly IPluginFinder _pluginFinder;
        private readonly ICountryService _countryService;
		private readonly ICommonServices _services;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IAsyncState _asyncState;

        #endregion

        #region Constructors

        public LanguageController(
            ILanguageService languageService,
			IStoreMappingService storeMappingService,
            IGenericAttributeService genericAttributeService,
            AdminAreaSettings adminAreaSettings,
			IPluginFinder pluginFinder,
            ICountryService countryService,
			ICommonServices services,
            IDateTimeHelper dateTimeHelper,
            IAsyncState asyncState)
        {
            _languageService = languageService;
			_storeMappingService = storeMappingService;
            _genericAttributeService = genericAttributeService;
            _adminAreaSettings = adminAreaSettings;
			_pluginFinder = pluginFinder;
			_countryService = countryService;
			_services = services;
            _dateTimeHelper = dateTimeHelper;
            _asyncState = asyncState;
        }

		#endregion

		#region Utilities

		private void PrepareLanguageModel(LanguageModel model, Language language, bool excludeProperties)
		{
			var allCultures = CultureInfo.GetCultures(CultureTypes.SpecificCultures)
				.OrderBy(x => x.DisplayName)
				.ToList();

			var allCountryNames = _countryService.GetAllCountries(true)
				.ToDictionarySafe(x => x.TwoLetterIsoCode.EmptyNull().ToLower(), x => x.GetLocalized(y => y.Name, _services.WorkContext.WorkingLanguage, true, false));

			model.AvailableCultures = allCultures
				.Select(x => new SelectListItem { Text = "{0} [{1}]".FormatInvariant(x.DisplayName, x.IetfLanguageTag), Value = x.IetfLanguageTag })
				.ToList();

			model.AvailableTwoLetterLanguageCodes = new List<SelectListItem>();
			model.AvailableFlags = new List<SelectListItem>();

			foreach (var item in allCultures)
			{
				if (!model.AvailableTwoLetterLanguageCodes.Any(x => x.Value.IsCaseInsensitiveEqual(item.TwoLetterISOLanguageName)))
				{
					// Display language name is not provided by net framework
					var index = item.DisplayName.EmptyNull().IndexOf(" (");

					if (index == -1)
						index = item.DisplayName.EmptyNull().IndexOf(" [");

					var displayName = "{0} [{1}]".FormatInvariant(
						index == -1 ? item.DisplayName : item.DisplayName.Substring(0, index),
						item.TwoLetterISOLanguageName);

                    if (item.TwoLetterISOLanguageName.Length == 2)
                    { 
					    model.AvailableTwoLetterLanguageCodes.Add(new SelectListItem { Text = displayName, Value = item.TwoLetterISOLanguageName });
                    }
				}
			}

			foreach (var path in Directory.EnumerateFiles(_services.WebHelper.MapPath("~/Content/Images/flags/"), "*.png", SearchOption.TopDirectoryOnly))
			{
				var name = Path.GetFileNameWithoutExtension(path).EmptyNull().ToLower();
				string countryDescription = null;

				if (allCountryNames.ContainsKey(name))
					countryDescription = "{0} [{1}]".FormatInvariant(allCountryNames[name], name);
				
				if (countryDescription.IsEmpty())
					countryDescription = name;

				model.AvailableFlags.Add(new SelectListItem { Text = countryDescription, Value = Path.GetFileName(path) });
			}

			if (!excludeProperties)
			{
				model.SelectedStoreIds = _storeMappingService.GetStoresIdsWithAccess(language);
			}

			model.AvailableFlags = model.AvailableFlags.OrderBy(x => x.Text).ToList();
			model.AvailableStores = _services.StoreService.GetAllStores().ToSelectListItems(model.SelectedStoreIds);

			if (language != null)
			{
				var lastImportInfos = GetLastResourcesImportInfos();
				if (lastImportInfos.TryGetValue(language.Id, out LastResourcesImportInfo info))
				{
					model.LastResourcesImportOn = info.ImportedOn;
					model.LastResourcesImportOnString = model.LastResourcesImportOn.Value.RelativeFormat(false, "f");
				}
			}
		}

		private void PrepareAvailableLanguageModel(
            AvailableLanguageModel model,
            AvailableResourcesModel resources,
            Dictionary<int, LastResourcesImportInfo> lastImportInfos,
            Language language = null,
            LanguageDownloadState state = null)
        {
            // Source Id (aka SetId), not entity Id!
            model.Id = resources.Id;
			model.PreviousSetId = resources.PreviousSetId;
            model.IsInstalled = language != null;
            model.Name = GetCultureDisplayName(resources.Language.Culture) ?? resources.Language.Name;
            model.LanguageCulture = resources.Language.Culture;
            model.UniqueSeoCode = resources.Language.TwoLetterIsoCode;
            model.Rtl = resources.Language.Rtl;
            model.Version = resources.Version;
            model.Type = resources.Type;
			model.Published = resources.Published;
			model.DisplayOrder = resources.DisplayOrder;
			model.TranslatedCount = resources.TranslatedCount;
			model.TranslatedPercentage = resources.TranslatedPercentage;
            model.IsDownloadRunning = state != null && state.Id == resources.Id;
            model.UpdatedOn = _dateTimeHelper.ConvertToUserTime(resources.UpdatedOn, DateTimeKind.Utc);
            model.UpdatedOnString = model.UpdatedOn.RelativeFormat(false, "f");
            model.FlagImageFileName = GetFlagFileName(resources.Language.Culture);

            if (language != null && lastImportInfos.TryGetValue(language.Id, out LastResourcesImportInfo info))
            {
                // Only show percent at last import if it's less than the current percentage.
                var percentAtLastImport = Math.Round(info.TranslatedPercentage, 2);
                if (percentAtLastImport < model.TranslatedPercentage)
                {
                    model.TranslatedPercentageAtLastImport = percentAtLastImport;
                }

				model.LastResourcesImportOn = info.ImportedOn;
				model.LastResourcesImportOnString = model.LastResourcesImportOn.Value.RelativeFormat(false, "f");
			}
		}

        private async Task<CheckAvailableResourcesResult> CheckAvailableResources(bool enforce = false)
        {
            var cacheKey = "admin:language:checkavailableresourcesresult";
            var currentVersion = SmartStoreVersion.CurrentFullVersion;
            CheckAvailableResourcesResult result = null;
            string jsonString = null;

            if (!enforce)
            {
                jsonString = Session[cacheKey] as string;
            }

            if (jsonString == null)
            {
                try
                {
                    using (var client = new HttpClient())
                    {
                        client.Timeout = TimeSpan.FromMilliseconds(10000);
                        client.DefaultRequestHeaders.Accept.Clear();
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        client.DefaultRequestHeaders.UserAgent.ParseAdd("SmartStore.NET " + currentVersion);
                        client.DefaultRequestHeaders.Add("Authorization-Key", Services.StoreContext.CurrentStore.Url.EmptyNull().TrimEnd('/'));

                        var url = CommonHelper.GetAppSetting<string>("sm:TranslateCheckUrl").FormatInvariant(currentVersion);
                        var response = await client.GetAsync(url);

                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            jsonString = await response.Content.ReadAsStringAsync();
                            Session[cacheKey] = jsonString;
                        }
                    }
                }
                catch (Exception ex)
                {
                    NotifyError(T("Admin.Configuration.Languages.CheckAvailableLanguagesFailed"));
                    Logger.ErrorsAll(ex);
                }
            }

            if (jsonString.HasValue())
            {
                result = JsonConvert.DeserializeObject<CheckAvailableResourcesResult>(jsonString);
            }

            return result ?? new CheckAvailableResourcesResult();
        }

        private async Task<string> DownloadAvailableResources(string downloadUrl, string storeUrl)
        {
            Guard.NotEmpty(downloadUrl, nameof(downloadUrl));

src/Presentation/SmartStore.Web/Administration/Views/Language/Create.cshtml
@model LanguageModel
@{
    ViewBag.Title = T("Admin.Configuration.Languages.AddNew").Text;
}
@using (Html.BeginForm())
{
    <div class="section-header">
        <div class="title">
            <i class="fa fa-language"></i>
            @T("Admin.Configuration.Languages.AddNew") @Html.ActionLink("(" + T("Admin.Configuration.Languages.BackToList") + ")", "List")
        </div>
        <div class="options">
            <button type="submit" name="save" value="save" class="btn btn-primary">
				<i class="fa fa-check"></i>
				<span>@T("Admin.Common.Save")</span>
			</button>
            <button type="submit" name="save" value="save-continue" class="btn btn-secondary">
				<span>@T("Admin.Common.SaveContinue")</span>
			</button>
        </div>
    </div>

    Html.RenderPartial("_CreateOrUpdate", Model);
}

src/Presentation/SmartStore.Web/Administration/Views/Language/Edit.cshtml
@model LanguageModel
@using Telerik.Web.Mvc.UI
@{
    ViewBag.Title = T("Admin.Configuration.Languages.EditLanguageDetails").Text;
}
@using (Html.BeginForm())
{
    <div class="section-header">
        <div class="title">
            <i class="fa fa-language"></i>
            @T("Admin.Configuration.Languages.EditLanguageDetails") - @Model.Name @Html.ActionLink("(" + T("Admin.Configuration.Languages.BackToList") + ")", "List")
        </div>
        <div class="options">
            <button type="submit" name="save" value="save" class="btn btn-warning">
                <i class="fa fa-check"></i>
				<span>@T("Admin.Common.Save")</span>
            </button>
            <button type="submit" name="save" value="save-continue" class="btn btn-secondary">
                <span>@T("Admin.Common.SaveContinue")</span>
            </button>
            <a href="@Url.Action("ExportXml", new { id = Model.Id })" class="btn btn-secondary" onclick='return confirm(@T("Admin.Common.AskToProceed").JsText);'>
                <i class="fa fa-upload"></i>
				<span>@T("Admin.Configuration.Languages.Export")</span>
            </a>
            <a href="#importxml-window" data-toggle="modal" class="btn btn-secondary">
                <i class="fa fa-download"></i>
				<span>@T("Admin.Configuration.Languages.Import")</span>
            </a>
            <button type="submit" id="language-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
				<span>@T("Admin.Common.Delete")</span>
            </button>
        </div>
    </div>

    Html.RenderPartial("_CreateOrUpdate", Model);
}
@Html.DeleteConfirmation("language-delete")

@*Import resources dialog*@
@{Html.SmartStore().Window()
    .Name("importxml-window")
    .Title(T("Admin.Configuration.Languages.Import"))
    .Content(@<text>

	<form enctype="multipart/form-data" method="POST" action="@Url.Action("ImportXml", "Language", new { id = Model.Id })">

        @Html.SmartStore().TabStrip().Name("language-import-tab").Style(TabsStyle.Material).Position(TabsPosition.Top).Items(x =>
        {
            x.Add().Text(T("Admin.Configuration.Languages.XmlFile").Text).Content(TabImportXmlFile()).Selected(true);
            x.Add().Text(T("Common.Download").Text).Content(TabImportDownload());
            EngineContext.Current.Resolve<IEventPublisher>().Publish(new TabStripCreated(x, "language-import-tab", this.Html, this.Model));
        })
		
        <div class="mt-3">
			<div class="form-check">
				@Html.RadioButton("mode", "3", true, new { id = "importxmlmode_3", @class = "form-check-input" })
				<label class="form-check-label" for="importxmlmode_3">@T("Admin.Configuration.Languages.Import.InsertUpdate")</label>
			</div>
			<div class="form-check">
				@Html.RadioButton("mode", "1", false, new { id = "importxmlmode_1", @class = "form-check-input" })
				<label class="form-check-label" for="importxmlmode_1">@T("Admin.Configuration.Languages.Import.Insert")</label>
			</div>
			<div class="form-check">
				@Html.RadioButton("mode", "2", false, new { id = "importxmlmode_2", @class = "form-check-input" })
				<label class="form-check-label" for="importxmlmode_2">@T("Admin.Configuration.Languages.Import.Update")</label>
			</div>
			<hr />
			<div class="form-check">
				@Html.CheckBox("updatetouched", false, new { id = "importxmlupdatetouched", @class = "form-check-input" })
				<label class="form-check-label" for="importxmlupdatetouched">@T("Admin.Configuration.Languages.Import.UpdateTouched")</label>
			</div>
        </div>
    </form>
    </text>)
    .FooterContent(@<text>
        <a href="#" class="btn btn-secondary btn-flat" data-dismiss="modal">
			<span>@T("Common.Cancel")</span>
		</a>
		<button id="importxmlsubmit" type="button" class="btn btn-primary">
			<i class="fa fa-download"></i>
			<span>@T("Admin.Configuration.Languages.Import")</span>
		</button>
    </text>)
    .Size(WindowSize.Large)
    .Render();
}

@helper TabImportXmlFile()
{
    <div class="form-group">
        <input type="file" id="importxmlfile" name="importxmlfile" class="form-control-file" accept=".xml" />
    </div>
}

@helper TabImportDownload()
{
    <div>
        @if (Model.AvailableDownloadLanguages.Any())
        {
            <table class="adminContent">
                <tr class="wide">
                    <td class="adminTitle">
                        @Html.SmartLabelFor(model => model.AvailableLanguageSetId)
                    </td>
                    <td class="adminData">
                        <select id="@Html.FieldIdFor(x => x.AvailableLanguageSetId)" name="@Html.FieldNameFor(x => x.AvailableLanguageSetId)" 
                                class="form-control form-control-lg select-customtemplate drop-customtemplate" data-placeholder="@T("Common.Unspecified")">
                            <option></option>
                            @foreach (var item in Model.AvailableDownloadLanguages.OrderBy(x => x.DisplayOrder))
                            {
                                var translated = T("Admin.Configuration.Languages.TranslatedPercentage", item.TranslatedPercentage.ToString("G29"));
                                if (item.TranslatedPercentageAtLastImport.HasValue)
                                {
                                    translated = string.Concat(
                                        translated,
                                        ". ",
                                        T("Admin.Configuration.Languages.TranslatedPercentageAtLastImport", item.TranslatedPercentageAtLastImport.Value.ToString("G29")));
                                }
                                <option value="@item.Id" data-imagename="@item.FlagImageFileName" data-translated="@(translated).">@item.Name</option>
                            }
                        </select>
                        @Html.ValidationMessageFor(model => model.AvailableLanguageSetId)
                    </td>
                </tr>
            </table>
        }
        else
        {
            <div class="alert alert-warning">
                @T("Admin.Configuration.Languages.NoAvailableLanguagesFound", SmartStoreVersion.CurrentFullVersion)
            </div>
        }
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {

        // Submit resources import form
        $("#importxmlsubmit").click(function (e) {
            e.preventDefault();
            $('#importxml-window').find("form").submit();
        });

        // Import mode changed
        $("#importxml-window input[name=mode]").on("change", function (e) {
            var id = $(this).attr("id");
            var chk = $("#importxmlupdatetouched");
            if (id == "importxmlmode_1") {
                chk.attr("disabled", "true").parent().find(">span").addClass("muted");
            }
            else {
                chk.removeAttr("disabled").parent().find(">span").removeClass("muted");
            }
        });

        //
        $('#@Html.FieldIdFor(x => x.AvailableLanguageSetId)').selectWrapper({
            allowClear: true,
            minimumResultsForSearch: 16,
            templateResult: availableLanguagesSelectItemFormatting,
            templateSelection: availableLanguagesSelectItemFormatting
        });

        function availableLanguagesSelectItemFormatting(item) {
            try {
                var option = $(item.element);

                if (option.length === 0) {
                    option = $('#@Html.FieldIdFor(x => x.AvailableLanguageSetId)').find('option[value="' + item.id + '"]');
                }

				var html = '<div class="form-row flex-nowrap align-items-center">',
                    imageName = option.attr('data-imagename');

                if (imageName.length > 0) {
					//html += '<img src="@Url.Content("~/Content/Images/flags/")' + imageName + '" style="float: left; margin-top: 3px;" />';
					html += '<div class="col" style="max-width:48px; width:48px"><div class="img-center-container"><img class="img-fluid" src="@Url.Content("~/Content/Images/flags/")' + imageName + '" /></div></div>';
				}

				html += '<div class="col">';
				html += '<div class="fs-xs font-weight-medium">' + item.text + '</div>';
				html += '<div class="text-muted fs-xs">' + option.attr('data-translated') + '</div>';
                html += '</div>';
                html += '</div>';

                return $(html);
            }
            catch (e) { }

            return item.text;
        }
    });
</script>

src/Presentation/SmartStore.Web/Administration/Views/Language/List.cshtml
@using SmartStore.Admin.Models.Localization;
@model List<LanguageModel>
@{
    ViewBag.Title = T("Admin.Configuration.Languages").Text;

    var defaultLanguageNote = ViewBag.DefaultLanguageNote as string;
}
<div class="section-header">
    <div class="title">
        <i class="fa fa-language"></i>
        @T("Admin.Configuration.Languages")
    </div>
    <div class="options">
        <a href="@Url.Action("Create")" class="btn btn-primary">
			<i class="fa fa-plus"></i>
			<span>@T("Admin.Common.AddNew")</span>
		</a>
    </div>
</div>

<div>
	<h5 class="mb-3">@T("Admin.Configuration.Languages.InstalledLanguages")</h5>
    @if (defaultLanguageNote.HasValue())
    {
        <div class="alert alert-info">
            @Html.Raw(defaultLanguageNote)
        </div>
    }

	<div class="table-responsive">
		<table class="table admin-table installed-languages-list language-list">
			<thead>
				<tr>
					<th style="width: 350px;">@T("Admin.Configuration.Languages.Fields.Name")</th>
					<th style="width: 160px;" class="text-center">@T("Admin.Configuration.Languages.Fields.LanguageCulture")</th>
					<th style="width: 140px;" class="text-center">@T("Admin.Configuration.Languages.Fields.UniqueSeoCode")</th>
					<th style="width: 160px;" class="text-center">@T("Admin.Configuration.Languages.Fields.Published")</th>
					<th style="width: 200px;">@T("Admin.Configuration.Languages.Fields.LastResourcesImportOn")</th>
					<th style="width: 160px;" class="text-center">@T("Admin.Common.Store.LimitedTo")</th>
					<th class="text-center">@T("Common.DisplayOrder")</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var language in Model)
				{
					<tr class="@(language.Published ? "" : "disabled")">
						<td>
							@if (language.FlagImageFileName.HasValue())
							{
								<img src="@Url.Content("~/Content/images/flags/" + language.FlagImageFileName)" class="flag-icon mr-1 mb-1" />
							}
							<a href="@Url.Action("Edit", new { id = language.Id })">@language.Name</a>
						</td>
						<td class="text-center">
							@language.LanguageCulture
						</td>
						<td class="text-center">
							@language.UniqueSeoCode
						</td>
						<td class="text-center">
							@Html.SymbolForBool(language.Published)
						</td>
						<td>
							@if (language.LastResourcesImportOn.HasValue)
							{
								<span title="@language.LastResourcesImportOn.Value.ToString()">@language.LastResourcesImportOnString</span>
							}
							else
							{
								@Html.SymbolForBool(false)
							}
						</td>
						<td class="text-center">
							@Html.SymbolForBool(language.LimitedToStores)
						</td>
						<td class="text-center">
							@language.DisplayOrder
						</td>
						<td class="omega text-truncate">
							<a href="@Url.Action("Edit", new { id = language.Id })" class="btn btn-warning btn-sm">
								<span>@T("Admin.Common.Edit")</span>
							</a>
							<a href="@Url.Action("Resources", new { languageId = language.Id })" class="btn btn-secondary btn-sm">
								<span>@T("Admin.Configuration.Languages.Resources.View")</span>
							</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

<div class="mt-5">
	<h5 class="mb-3">@T("Admin.Configuration.Languages.AvailableLanguages")</h5>
    <div id="AvailableLanguages"></div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        // Load available languages.
	    $({}).doAjax({
	        url: '@Url.Action("AvailableLanguages")',
	        smallIcon: '#AvailableLanguages',
	        callbackSuccess: function (resp) {
	            $('#AvailableLanguages').html(resp);
	        }
	    });

        // Watch language download progress.
		SmartStore.Admin.TaskWatcher.startWatching({
            context: $('#AvailableLanguages'),
            elementsSelector: '.task-progress',
            defaultProgressMessage: @T("Admin.System.ScheduleTasks.RunNow.IsRunning").JsText,
            pollUrl: '@Url.Action("DownloadProgress")',
            onTaskStarted: function (task, el) {
                var tr = el.closest('tr');

                $('#AvailableLanguages').find('a.download-language').addClass('hide');
                $('body, html').animate({ scrollTop: tr.offset().top }, 'slow');
            },
            onTaskCompleted: function (taskId, el) {
               window.location = '@Url.Action("List")';
            }
        });
    });
</script>

src/Presentation/SmartStore.Web/Administration/Views/Language/Resources.cshtml
@model Telerik.Web.Mvc.GridModel<LanguageResourceModel>
@using Telerik.Web.Mvc.UI;
@{
    var gridPageSize = EngineContext.Current.Resolve<SmartStore.Core.Domain.Common.AdminAreaSettings>().GridPageSize;
    ViewBag.Title = T("Admin.Configuration.Languages.Localization").Text;
}
<div class="section-header">
    <div class="title">
        <i class="fa fa-language"></i>
        @T("Admin.Configuration.Languages.Localization") - @Html.ActionLink("(" + T("Admin.Configuration.Languages.BackToList") + ")", "List")
    </div>
</div>

@if (ViewBag.AllLanguages != null)
{
    <p>
        <table class="adminContent">
            <tr>
                <td class="adminTitle">
                    @Html.SmartLabel("localeresource-language", T("Admin.Configuration.Languages.Select"))
                </td>
                <td class="adminData">
                    @Html.DropDownList("localeresource-language", (IEnumerable<SelectListItem>)ViewBag.AllLanguages, new { onchange = "onLocaleResourceLanguageSelected(this.value);" })

                    <script type="text/javascript">
                        function onLocaleResourceLanguageSelected(languageid) {
                            window.location = '@(Url.Action("Resources") + "?languageId=")' + languageid;
                        }
                    </script>
                </td>
            </tr>
        </table>
    </p>
}

<div class="alert alert-info alert-dismissible">
	@T("Admin.Configuration.Languages.Resources.Description")
	<button type="button" class="close" data-dismiss="alert">&times;</button>
</div>   

<div>
	@(Html.Telerik().Grid<LanguageResourceModel>()
		.Name("resources-grid")
		.DataKeys(x =>
		{
			x.Add(y => y.Id).RouteKey("Id");
			x.Add(y => y.LanguageId).RouteKey("languageId");
		})
		.Columns(columns =>
		{
			columns.Bound(x => x.LanguageName)
				.Width("10%")
				.ReadOnly()
				.Filterable(false);
			columns.Bound(x => x.ResourceName).Width("30%");
			columns.Bound(x => x.ResourceValue).EditorTemplateName("MultilineText").Width("60%");
			columns.Command(commands =>
			{
				commands.Edit().Localize(T);
				commands.Delete().Localize(T);
			});

		})
		.ToolBar(x => x.Insert())
		.Editable(x =>
		{
			x.Mode(GridEditMode.InLine);
		})
		.Filterable()
		.Pageable(settings => settings.PageSize(gridPageSize).Total(Model.Total).Position(GridPagerPosition.Both))
		.DataBinding(dataBinding =>
		{
			dataBinding.Ajax().Select("Resources", "Language")
				.Update("ResourceUpdate", "Language")
				.Delete("ResourceDelete", "Language")
				.Insert("ResourceAdd", "Language", new { id = ViewBag.LanguageId });
		})
		.EnableCustomBinding(true)
		.PreserveGridState()
		.ClientEvents(x => x.OnEdit("onResourceEdit"))
		.ClientEvents(x => x.OnError("Grid_onError")))
</div>

<script type="text/javascript">
    function onResourceEdit(e) {
        if (e.mode == "insert") {
            $(e.form).find("td:first").html("@ViewBag.LanguageName");
        }
    }
    function Grid_onError(e) {
        alert(e.XMLHttpRequest.responseText);
        e.preventDefault();
    }
</script>